baseURL = "https://nar-uq.org/"
languageCode = "ru"
title = "NAR-UQ"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ru]
    languageName = "RU"
    weight = 1
    title = "NAR-UQ — Словесность"
  [languages.en]
    languageName = "EN"
    weight = 2
    title = "NAR-UQ — Wordry"
  [languages.kk]
    languageName = "KK"
    weight = 3
    title = "NAR-UQ — Сөздік"

[params]
  description = "Словесность без посредников"
  author = "Серик Болатжанович Рысжанов"
  accentColor = "#1a6b6b"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
